"""add payments and live tracking fields

Revision ID: 875d694ae8a5
Revises: b207592b6d67
Create Date: 2026-07-18 23:02:52.881051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875d694ae8a5'
down_revision: Union[str, None] = 'b207592b6d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate wrongly flags PostGIS's own internal 'spatial_ref_sys'
    # table for deletion since it's not part of our models. Never drop it.
    op.add_column('bookings', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('razorpay_order_id', sa.String(length=64), nullable=True))
    op.add_column('bookings', sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True))
    op.add_column('rides', sa.Column('is_sharing_location', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('rides', sa.Column('current_lat', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('rides', sa.Column('current_lng', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('rides', sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'location_updated_at')
    op.drop_column('rides', 'current_lng')
    op.drop_column('rides', 'current_lat')
    op.drop_column('rides', 'is_sharing_location')
    op.drop_column('bookings', 'razorpay_payment_id')
    op.drop_column('bookings', 'razorpay_order_id')
    op.drop_column('bookings', 'amount')
    # ### end Alembic commands ###
