"""initial schema

Revision ID: b207592b6d67
Revises: 
Create Date: 2026-07-18 16:40:59.563776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'b207592b6d67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('seating_capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_vehicles_organization_id'), 'vehicles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vehicles_owner_id'), 'vehicles', ['owner_id'], unique=False)
    op.create_table('rides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('pickup_address', sa.String(length=500), nullable=False),
    sa.Column('destination_address', sa.String(length=500), nullable=False),
    sa.Column('pickup_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('destination_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('route_geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seats_total', sa.Integer(), nullable=False),
    sa.Column('seats_available', sa.Integer(), nullable=False),
    sa.Column('fare_per_seat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PUBLISHED', 'STARTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='ridestatus'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: GeoAlchemy2's Geometry columns auto-create their own GIST spatial
    # index via a DDL event when the table is created (spatial_index=True by
    # default). The explicit create_index calls autogenerate produced for
    # pickup_location/destination_location/route_geometry are removed here
    # to avoid a duplicate-index error.
    op.create_index(op.f('ix_rides_driver_id'), 'rides', ['driver_id'], unique=False)
    op.create_index(op.f('ix_rides_organization_id'), 'rides', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rides_vehicle_id'), 'rides', ['vehicle_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('seats_booked', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'STARTED', 'IN_PROGRESS', 'COMPLETED', 'PAYMENT_PENDING', 'PAYMENT_COMPLETED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_organization_id'), 'bookings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bookings_passenger_id'), 'bookings', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_bookings_ride_id'), 'bookings', ['ride_id'], unique=False)
    # NOTE: autogenerate wrongly flagged PostGIS's own internal 'spatial_ref_sys'
    # table for deletion since it's not part of our models. Never drop it.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_ride_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_passenger_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_organization_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_rides_vehicle_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_organization_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_driver_id'), table_name='rides')
    op.drop_table('rides')
    op.drop_index(op.f('ix_vehicles_owner_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_organization_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
